# Site
title:              Yet Another Geek Blog
bio:                'Yet Another Geek Blog : dev with fun(ction)'
description:        "Yet Another Geek Blog : dev with fun(ction)"
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cboudereau.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cboudereau
github_username:  cboudereau

# Jekyll
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   yagb

# Social
analytics-id:       "default"
twitter:            cboudereau
github:             cboudereau
3dwarehouse:        0581142414212066722209576/Cl%C3%A9ment-B

# personal
location:           France, FR
email:              cboudereau@gmail.com

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
